import presidentImg from '../assets/president.jpg';

export default function AboutUs() {
  return <article className="about-page">
    <header className="about-page-hero"><p className="eyebrow">Our story</p><h1>About Amar Seva Sangam USA</h1><p>Amar Seva Sangam USA is the American chapter of a global movement to empower persons with disabilities. We raise awareness, mobilize resources, and connect donors and volunteers in the U.S. to life-changing rehabilitation, education, and community programs in India.</p><div className="about-highlights"><span><b>1981</b>Our roots began</span><span><b>3 countries</b>One shared mission</span><span><b>501(c)(3)</b>U.S. nonprofit</span></div></header>
    <section className="content-block"><h2>Who We Are</h2><p>The USA chapter extends the impact of Amar Seva Sangam India, a globally recognized organization founded in 1981. Our goal is to gather support, volunteers, and resources to empower persons with disabilities and strengthen programs in India.</p><p>As a U.S. nonprofit with 501(c)(3) status, we serve as the American bridge—connecting generosity here with practical, life-changing programs in India.</p></section>
    <section className="content-block"><h2>Our Mission</h2><p>To empower persons with disabilities by advancing inclusive, community-driven support systems, providing a full range of education and rehabilitation services, and mobilising resources globally.</p></section>
    <section className="content-block"><h2>Our Story & Roots</h2><p>Amar Seva Sangam was founded in June 1981 by Sri S. Ramakrishnan—himself living with a spinal injury—starting with just five rural children under a thatched roof. In 1992, CA S. Sankara Raman, a wheelchair user affected by muscular dystrophy, joined as Promoter & Secretary.</p><p>Over four decades, that small effort has grown into a far-reaching movement for disability inclusion across rural Tamil Nadu. Founder President S. Ramakrishnan was awarded the Padma Shri in 2020, one of India’s highest civilian honors, for this work.</p></section>
    <section className="content-block"><h2>Our Global Family</h2><div className="global-family"><div><h3>Amar Seva Sangam (India)</h3><p>The founding organization and source of the on-the-ground programs, based in Ayikudy Village, Tenkasi District, Tamil Nadu. Founded in 1981, it has grown from a single primary school into a 30-acre barrier-free campus and a regional catalyst for disability inclusion through community rehabilitation, early intervention, and inclusive education.</p></div><div><h3>Handi-Care Intl. (Canada)</h3><p>A Canadian registered charity founded in 1992 by Sulo Krishnamurthy and run entirely by volunteers. For more than 30 years, it has supported rehabilitation, education, empowerment, assistive technology, clinical placements, and family support. Its Pediatric Assistive Technology Provision Program received a 2023 Zero Project Award.</p></div></div><p>Together, we form one mission across three countries—from villages in Tamil Nadu, to volunteer-led fundraising in Toronto, to this chapter in the United States.</p></section>
    <section className="president-message content-block"><div className="president-message-head"><div><h2>Message From the President</h2><p className="president-org">Amar Seva Sangam USA</p></div></div><figure className="president-portrait"><img src={presidentImg} alt="Geetha Padaki, President of Amar Seva Sangam USA" /><figcaption>Geetha Padaki<br /><span>President, Amar Seva Sangam USA</span></figcaption></figure><div className="president-letter"><p><strong>Dear Friends and Well-Wishers,</strong></p><p>It is with gratitude and purpose that I share an important milestone—the incorporation of Amar Seva Sangam USA and the receipt of our 501(c)(3) nonprofit status. This step strengthens the long-standing mission of Amar Seva Sangam in India, in partnership with Handicare Intl., a Canadian registered charity of over 30 years, to serve persons with disabilities and special needs with compassion, dignity, and inclusion.</p><p>Amar Seva Sangam USA is committed to building awareness and mobilizing resources to support programs in rehabilitation, education, healthcare, and livelihood development. As a U.S.-based organization, we serve as a bridge—connecting generous hearts and meaningful action across borders to create lasting impact.</p><p>I invite you to be part of this mission. Your donations and support will directly enable life-changing services, helping individuals with disabilities lead more independent and dignified lives. Together, we can transform compassion into tangible outcomes.</p><p>Thank you to our board members, volunteers, donors, and partners for believing in this vision. I encourage you to join us—through your contributions, advocacy, and engagement—as we uphold the founding spirit of Amar Seva Sangam.</p><p className="president-signoff">With sincere appreciation,<br /><strong>Geetha Padaki</strong><br />President<br />Amar Seva Sangam USA</p></div></section>
    <section className="get-involved"><p className="eyebrow">Be part of the change</p><h2>Help create a more inclusive tomorrow</h2><p className="get-involved-lead">Your support turns compassion into practical care, education, independence, and opportunity for persons with disabilities and their families.</p><div className="giving-choices"><span>Give today to support life-changing programs</span><span>Volunteer your time and skills</span><span>Share our mission with your community</span></div><div className="cta-row"><a href="/#donate" className="btn hero-cta get-involved-donate">Make a Donation</a><a href="mailto:contact@amarsevausa.org" className="btn hero-secondary-cta">Volunteer / Contact Us</a></div><p className="get-involved-note">Every contribution, of any size, helps move this mission forward.</p></section>
  </article>;
}
