import ProgramPage from './ProgramPage';
const services = [
  ['Early Intervention', 'Identifies and treats developmental delays and disabilities in children aged 0–6, helping prevent long-term impairments and improve quality of life. The Enabling Inclusion® model brings technology-driven care, parental empowerment, specialized therapy, and community screening directly to homes and local communities.'],
  ['Medical Rehabilitation Center & Inpatient/Outpatient Care', 'Round-the-clock specialized care for people with spinal cord injuries, stroke, cerebral palsy, muscular dystrophy, and other neurological and musculoskeletal conditions. Intensive, structured rehabilitation helps prevent complications, restore function, and support a safe return home and into the community.'],
  ['Physical Therapy Services', 'State-of-the-art physiotherapy equipment, manual therapy, and pool environments help reduce joint strain, alleviate pain, build muscle endurance, improve circulation, and restore motor skills.'],
  ['Occupational Therapy & Daily Living Skills', 'Practical functional training helps people dress, bathe, eat, transfer positions, and navigate physical obstacles with greater independence and ease.'],
  ['Speech Therapy & Audiology Services', 'Specialized diagnostics and treatment plans support children and adults experiencing speech delays, hearing loss, or swallowing difficulties—enabling clearer communication and inclusion at home and school.'],
  ['Custom Prosthetics & Orthotics Workshop', 'On-site technicians craft custom artificial limbs, calipers, splints, and adaptive wheelchairs designed for rural terrain. Free or subsidized devices remove physical barriers at home, school, and work.'],
];
export default function Therapies() { return <ProgramPage eyebrow="Our programs" title="Therapies & Healthcare" intro="A multidisciplinary clinical ecosystem delivering specialized medical intervention, daily physical restoration, and assistive technology." sourceUrl="https://www.amarseva.org/institute-based-rehabilitation/">{services.map(([heading, copy]) => <section className="content-block" key={heading}><h2>{heading}</h2><p>{copy}</p></section>)}</ProgramPage>; }
